name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm clean-install
      - run: npm test -- --coverage
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-site
          path: ./dist

  versioning:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 1
    outputs:
      tag: ${{ steps.compute.outputs.tag }}
      version: ${{ steps.compute.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Compute version
        id: compute
        run: |
          calver=$(date +'%y.%U')
          minor=$(git tag -l $calver.* | wc -l)
          tag=$calver.$minor
          version=$tag+$GITHUB_RUN_NUMBER
          echo $version
          echo "::set-output name=tag::$tag"
          echo "::set-output name=version::$version"

  docker:
    needs: versioning
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            estcequecestbientotleriznoir/web
          labels: |
            maintainer=jootl
            org.opencontainers.image.vendor=jootl
            org.opencontainers.image.authors=${{ secrets.JOOTL_MAIL }}
          tags: |
            type=ref,event=branch
            ${{ needs.versioning.outputs.tag }}
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
